version: '3'
services: 
  limesurvey6:
      image: acspri/limesurvey:6.4.5
      ports:
          - 8082:80
      environment:
          LIMESURVEY_DB_PASSWORD: example
          LIMESURVEY_ADMIN_USER: admin
          LIMESURVEY_ADMIN_PASSWORD: password
          LIMESURVEY_ADMIN_NAME: Lime Administrator
          LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
      volumes:
          - ./limesurvey/plugins:/var/www/html/plugins
          - ./limesurvey/upload:/var/www/html/upload
          - ./limesurvey/config:/var/www/html/application/config


  mysql:
      image: mariadb:lts
      volumes: 
          - mariadblts:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: example
      # demo passwords, change to something safe in production                

volumes:
  mariadblts: