version: '2'

services:

  limesurvey:
    image: adamzammit/limesurvey:6.6.1.1
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: example
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
    volumes:
      - ./plugins:/var/www/html/plugins
      - ./upload:/var/www/html/upload
      - ./config:/var/www/html/application/config
      - ./sessions:/var/lime/sessions

  mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example